# -*- coding: utf-8 -*-
"""
/***************************************************************************
 S111Viewer
                                 A QGIS plugin
 S-111 海洋數據可視化與動畫插件
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-16
        copyright            : (C) 2025 by NTOU
        email                : steven65026502@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load S111Viewer class from file S111Viewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .s111_viewer import S111Viewer
    return S111Viewer(iface)
